### ISSUE TITLE
Wrong rm command syntax on macOS

### ISSUE THREAD

**Issue by claudiofantacci** [robotology-playground/how-to-document-modules#3]
https://github.com/robotology/how-to-document-modules/blob/c7f2eced4dd6431e2766ab6046ba631887af253c/doxygen/doc-compile.sh#L7-L8

These two lines are not legal, they should be:
```bash
rm -rf doc
rm -rf $DESTINATION
```

**Comment by pattacini** [comment]
Fixed in `gh-pages` branch via `git push --force`.
Thanks @claudiofantacci 👍

**Comment by alecive** [comment]
Do they not work on mac only? They work on linux.

```
[alecive@m]$ mkdir test
[alecive@m]$ cd test/
[alecive@m]$ mkdir test
[alecive@m]$ rm test/ -rf
[alecive@m]$ ls
[alecive@m]$ cd ../
[alecive@m]$ rm test/ -rf
```

**Comment by claudiofantacci** [comment]
On macOS:
```bash
rm ./test -rf
rm: ./test: is a directory
rm: -rf: No such file or directory`
```
🙃

**Comment by pattacini** [comment]
AFAIK `rm -Rf something` is a Unix syntax, thus Mac, hence Linux too.

**Comment by claudiofantacci** [comment]
If you look at the man pages:

```bash
NAME
     rm, unlink -- remove directory entries

SYNOPSIS
     rm [-dfiPRrvW] file ...
```
there is actually a specific order between options and files/folders.

**Comment by alecive** [comment]
> there is actually a specific order between options and files/folders.

Sure, I know that it is better to put optional arguments in front, but still: it works perfectly fine on Linux if that is not the case.

**Comment by claudiofantacci** [comment]
To elaborate more my answer: macOS is not Linux.
It's based on on BSD and provides a different implementation of the `rm` (and other) core commands.

In this particular case the [Linux `rm`](https://www.gnu.org/software/coreutils/manual/html_node/rm-invocation.html#rm-invocation) is part of the `GNU coreutils`, while macOS `rm` comes from [BSD `rm`](http://man.openbsd.org/rm) (note that I linked the OpenBSD manpage, which is the most similar to macOS one).

`rm`, as part of the POSIX standard, is implemented in most UNIX-compliant OSs. They have the same interface, but the implementations may differ.

Anyway, it's funny that this actually happens on Linux systems and not BSD/macOS. I wonder whether there are security issues around this choices. Usually BSD maintainers are by far more focused and careful on security issues (for example BSD community fixed KRACK security issue at the beginning of the year!).
