### ISSUE TITLE
Migrate GitHub Actions script to use GITHUB_TOKEN

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/how-to-document-modules#4]
The GitHub Actions script in this repo still make use SSH Deploy keys, and as far as I can see this usage propagate to several repos in the robotology organization and on research line organizations (cc @GiulioRomualdi).

However, as of 2021 there are much more user friendly ways of pushing to a branch, such as using the GITHUB_TOKEN, see for example:
* https://github.com/robotology/idyntree/blob/v3.0.0/.github/workflows/ghpages.yml#L39
* https://github.com/robotology/funny-things/blob/v1.0.0/.github/workflows/gh-pages.yml#L53

We should eventually update this repo to use GITHUB_TOKEN as well, so that users that look to this repo for inspiration get to use the easiest option. Any volunteer for the task is welcome.

**Comment by pattacini** [comment]
Thanks @traversaro for pointing this out!
I'll be opening up a PR.
